# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"


Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.ssh.insert_key = false
  config.vbguest.auto_update=false # Deshabilitar actualizaciones automáticas de vbguest
  config.vm.define :lb_server do |lb| # Definir el servidor de balanceo de carga
    lb.vm.box = "centos6" # Importar el box de CentOS6 
    lb.vm.network :private_network, ip: "192.168.56.100" # Configurar la IP privada de la VM
    lb.vm.provider :virtualbox do |vb| # Asignar el proveedor de virtualización
      vb.customize ["modifyvm", :id, "--memory", "1024","--cpus", "1", "--name", "lb_server" ] # Configurar los recursos de la VM
    end
    lb.vm.provision :chef_solo do |chef| # Definir Chef solo como herramienta de aprovicionamiento de la VM
      chef.install = false # Deshabilitar la instalación de Chef solo
      chef.cookbooks_path = "cookbooks" # Establecer la ruta donde se encuentran las recetas de aprovisionamiento
      chef.add_recipe "haproxy" # Agregar la receta de aprovisionamiento de haproxy
      chef.json = {
        "web_servers" => [
          {"ip":"192.168.56.101"},
          {"ip":"192.168.56.102"}
         ]
      } # Definir las variables necesarias para configurar el haproxy
    end
  end
  config.vm.define :centos_web_1 do |wb| # Definir el servidor web 1
    wb.vm.box = "centos6" # Importar el box de CentOS6 
    wb.vm.network :private_network, ip: "192.168.56.101" # Configurar la IP privada de la VM
    wb.vm.network "public_network", bridge: "eth1", ip:"192.168.131.101", netmask: "255.255.255.0" # Configurar la IP pública de la VM
    wb.vm.provider :virtualbox do |vb| # Asignar el proveedor de virtualización
      vb.customize ["modifyvm", :id, "--memory", "1024","--cpus", "1", "--name", "centos_web_1" ] # Configurar los recursos de la VM
    end
    wb.vm.provision :chef_solo do |chef| # Definir Chef solo como herramienta de aprovicionamiento de la VM
      chef.cookbooks_path = "cookbooks" # Establecer la ruta donde se encuentran las recetas de aprovisionamiento
      chef.add_recipe "apache" # Agregar la receta de aprovisionamiento de apache 
      chef.json = {"service_name" => "Web server 1"} # Definir la variable que será usada para mostrar el nombre del servidor en index.html
    end
  end
  config.vm.define :centos_web_2 do |wb| # Definir el servidor web 2
    wb.vm.box = "centos6" # Importar el box de CentOS6 
    wb.vm.network :private_network, ip: "192.168.56.102" # Configurar la IP privada de la VM
    wb.vm.network "public_network", bridge: "eth1", ip:"192.168.131.102", netmask: "255.255.255.0" # Configurar la IP pública de la VM
    wb.vm.provider :virtualbox do |vb| # Asignar el proveedor de virtualización
      vb.customize ["modifyvm", :id, "--memory", "1024","--cpus", "1", "--name", "centos_web_2" ] # Configurar los recursos de la VM
    end
    wb.vm.provision :chef_solo do |chef| # Definir Chef solo como herramienta de aprovicionamiento de la VM
      chef.cookbooks_path = "cookbooks" # Establecer la ruta donde se encuentran las recetas de aprovisionamiento
      chef.add_recipe "apache"  # Agregar la receta de aprovisionamiento de haproxy
      chef.json = {"service_name" => "Web server 2"} # Definir la variable que será usada para mostrar el nombre del servidor en index.html
    end
  end
  config.vm.define :centos_database do |db| # Definir el servidor de base de datos
    db.vm.box = "centos6" # Importar el box de CentOS6 
    db.vm.network :private_network, ip: "192.168.56.103" # Configurar la IP privada de la VM
    db.vm.network "public_network", bridge: "eth1", ip:"192.168.131.103", netmask: "255.255.255.0" # Configurar la IP pública de la VM
    db.vm.provider :virtualbox do |vb| # Asignar el proveedor de virtualización
      vb.customize ["modifyvm", :id, "--memory", "1024","--cpus", "1", "--name", "centos_database" ] # Configurar los recursos de la VM
    end
    db.vm.provision :chef_solo do |chef| # Definir Chef solo como herramienta de aprovicionamiento de la VM
      chef.cookbooks_path = "cookbooks" # Establecer la ruta donde se encuentran las recetas de aprovisionamiento
      chef.add_recipe "mysql"  # Agregar la receta de aprovisionamiento de mysql
    end
  end
end
